// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "github.com/golang/mock/gomock"
)

// MockUserHandlerInterface is a mock of UserHandlerInterface interface.
type MockUserHandlerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUserHandlerInterfaceMockRecorder
}

// MockUserHandlerInterfaceMockRecorder is the mock recorder for MockUserHandlerInterface.
type MockUserHandlerInterfaceMockRecorder struct {
	mock *MockUserHandlerInterface
}

// NewMockUserHandlerInterface creates a new mock instance.
func NewMockUserHandlerInterface(ctrl *gomock.Controller) *MockUserHandlerInterface {
	mock := &MockUserHandlerInterface{ctrl: ctrl}
	mock.recorder = &MockUserHandlerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserHandlerInterface) EXPECT() *MockUserHandlerInterfaceMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockUserHandlerInterface) CreateUser(ctx *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CreateUser", ctx)
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUserHandlerInterfaceMockRecorder) CreateUser(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUserHandlerInterface)(nil).CreateUser), ctx)
}

// DeleteUser mocks base method.
func (m *MockUserHandlerInterface) DeleteUser(ctx *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DeleteUser", ctx)
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockUserHandlerInterfaceMockRecorder) DeleteUser(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockUserHandlerInterface)(nil).DeleteUser), ctx)
}

// FindUser mocks base method.
func (m *MockUserHandlerInterface) FindUser(ctx *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "FindUser", ctx)
}

// FindUser indicates an expected call of FindUser.
func (mr *MockUserHandlerInterfaceMockRecorder) FindUser(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUser", reflect.TypeOf((*MockUserHandlerInterface)(nil).FindUser), ctx)
}

// FindUsers mocks base method.
func (m *MockUserHandlerInterface) FindUsers(ctx *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "FindUsers", ctx)
}

// FindUsers indicates an expected call of FindUsers.
func (mr *MockUserHandlerInterfaceMockRecorder) FindUsers(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUsers", reflect.TypeOf((*MockUserHandlerInterface)(nil).FindUsers), ctx)
}

// UpdateUser mocks base method.
func (m *MockUserHandlerInterface) UpdateUser(ctx *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdateUser", ctx)
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockUserHandlerInterfaceMockRecorder) UpdateUser(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockUserHandlerInterface)(nil).UpdateUser), ctx)
}
